### ISSUE TITLE
Compare with official Cassandra chart

### ISSUE THREAD

**Issue by maver1ck** [MySocialApp/kubernetes-helm-chart-cassandra#5]
Quick search show there are two Cassandra charts available: yours and:
https://github.com/helm/charts/tree/master/incubator/cassandra

Can we merge features of both into official repo ?

**Comment by deimosfr** [comment]
Hi,

We may think about it. However I don't have time for the moment to do it. Are you interested into it?

Thanks

**Comment by maver1ck** [comment]
Yep. I'd like to port some of the features into official chart. Starting with Cassandra Exporter.
I will link PR here when they'll be ready.

**Comment by maver1ck** [comment]
I found following functionalities missing in official chart.
1) Custom env variables - this can replace custom Cassandra config
https://github.com/helm/charts/pull/8318
2) There is a bug with StatefulSet definition
https://github.com/helm/charts/pull/8320
3) Cassandra Exporter
https://github.com/helm/charts/pull/8325
4) Config files Overrides 
https://github.com/helm/charts/pull/8376
5) Pod disruption budget
https://github.com/helm/charts/pull/8381
6) Prometheus Operator support
7) Cassandra Reaper
I leave last 2 points for probably next few weeks

Anything else ?

**Comment by maver1ck** [comment]
@deimosfr 
From my point of view most of the work is done. 
I also became owner of official chart so if you'd like to contribute I'd be pleased.

**Comment by deimosfr** [comment]
Thanks @maver1ck , I'll add new stuffs in a short future, please continue to watch this repo in the case I miss to update the official chart.

Sorry, I really don't like working this way, but I need to go fast because I'm running my own company and I don't have time for the moment to deal with comments, waiting for approval etc...

I hope in a middle term, I'll be able to fully switch to the official one :)

**Comment by maver1ck** [comment]
@deimosfr Thanks for your chart.
It was very useful source of inspiration what to add to official one :)
